<template><div><blockquote>
<p>题目来源于<a href="https://adworld.xctf.org.cn/challenges/list" target="_blank" rel="noopener noreferrer">【攻防世界】<ExternalLinkIcon/></a></p>
</blockquote>
<h1 id="题目" tabindex="-1"><a class="header-anchor" href="#题目" aria-hidden="true">#</a> 题目</h1>
<ul>
<li>
<p>名称： base64</p>
</li>
<li>
<p>编号： GFSJ0522</p>
</li>
<li>
<p>难度:1</p>
</li>
<li>
<p>题目来源：<code v-pre>poxlove3</code></p>
</li>
<li>
<p>题目描述：
<code v-pre>元宵节灯谜是一种古老的传统民间观灯猜谜的习俗。 因为谜语能启迪智慧又饶有兴趣，灯谜增添节日气氛，是一项很有趣的活动。 你也很喜欢这个游戏，这不，今年元宵节，心里有个黑客梦的你，约上你青梅竹马的好伙伴小鱼， 来到了cyberpeace的攻防世界猜谜大会，也想着一展身手。 你们一起来到了小孩子叽叽喳喳吵吵闹闹的地方，你俩抬头一看，上面的大红灯笼上写着一些奇奇怪怪的 字符串，小鱼正纳闷呢，你神秘一笑，我知道这是什么了。</code></p>
</li>
<li>
<p>题目附件:
<code v-pre>Y3liZXJwZWFjZXtXZWxjb21lX3RvX25ld19Xb3JsZCF9</code></p>
</li>
</ul>
<h1 id="题解" tabindex="-1"><a class="header-anchor" href="#题解" aria-hidden="true">#</a> 题解</h1>
<ul>
<li>这个题实际上是没有任何难度的，从题目【Base64】就可以猜到，附件中的字符串应该是 <code v-pre>Base64</code> 转码之后的内容，随便找个<code v-pre>在线解码</code> 网站，就可以得到 <code v-pre>flag</code> ： <code v-pre>cyberpeace{Welcome_to_new_World!}</code>
<img src="https://img-blog.csdnimg.cn/e32042f7e13e4fe6a89bc1991d66bd34.png" alt="在这里插入图片描述" loading="lazy"></li>
</ul>
<h1 id="扩展" tabindex="-1"><a class="header-anchor" href="#扩展" aria-hidden="true">#</a> 扩展</h1>
<blockquote>
<p>这里主要聊一下 <code v-pre>Base64</code> 的原理。</p>
</blockquote>
<p>说到 <code v-pre>Base64</code>，就不得不说一个最让人觉得恶心的现象——<strong>乱码</strong>（想必都不陌生吧）。</p>
<ul>
<li><code v-pre>?  M&lt;+    7 Intel(R) </code></li>
<li><code v-pre>   鸀R執    	</code></li>
<li><code v-pre>锟斤拷·烫烫烫~</code></li>
</ul>
<blockquote>
<p>乱码究竟是如何产生的？</p>
</blockquote>
<p>其原因无非就一句话： 某种编码下对应的二进制符号在另一种编码下没有对应的字符，或者对应另一种字符。</p>
<p>举个例子： 假设 <code v-pre>BIG5</code> 编码下， <code v-pre>你</code> 对应的二进制为 <code v-pre>00001111</code>， <code v-pre>好</code> 对应的二进制为 <code v-pre>01110011</code>， 那么文字<code v-pre>你好</code>对应的二进制就为<code v-pre>0000111101110011</code>，而当用 <code v-pre>GBK2312</code>编码读取这两个字时，<code v-pre>00001111</code>对应的是<code v-pre>锟</code>，<code v-pre>01110011</code>对应的是空字符，那么读取到的内容就会变成 <code v-pre>锟</code>，也就是<strong>乱码</strong>。</p>
<blockquote>
<p><code v-pre>Base64</code> 和乱码有什么关系呢？</p>
</blockquote>
<p><code v-pre>Base64</code> 其实并不能称之为加/解密算法，准确来说，它应该是一个<strong>可读性算法</strong>。它的目的就是防止出现乱码，提升可读性。
<code v-pre>Base64</code> 是由 <code v-pre>A-Z</code>、<code v-pre>a-z</code>、<code v-pre>0-9</code> 这 <code v-pre>62</code> 个数字和字母，加上 <code v-pre>+</code> 和 <code v-pre>/</code> 这两个符号，共组成的 <code v-pre>64</code> 位基础符号。无论是哪种编码下的什么内容，经过 <code v-pre>Base64</code> 转换之后，都只会出现在这 <code v-pre>64</code> 个字符中（还有一个 <code v-pre>=</code> 比较特殊，不属于 <code v-pre>Base64</code> 但有时候也会出现，它是填充符号），不会出现其他的字符，也就不会出现乱码。</p>
<blockquote>
<p><code v-pre>Base64</code> 的原理是什么？是如何保证转码之后的信息在这<code v-pre>64</code> 个字符之内的？</p>
</blockquote>
<p>大多数计算机种，1 个字节占 8 个 bit位，而 <code v-pre>Base64</code> 则是将每 3 个字节（也就是 3 * 8 = 24  bit）拆分为 4 个 6 bit 的字节，如果要拆分的不足 3 个字节，则用填充符 <code v-pre>=</code> 来表示，也就是说，你最多可以看到两个 <code v-pre>=</code> 且一定在末尾。</p>
<p>6 bit 也就是说最大能表示的值为： <code v-pre>0011 1111</code>， 也就是 64。 这就是为什么能保证其转码结果一定在 64 个字符内的原因，因为最大值不可能大于 64。</p>
<blockquote>
<p>就用上面的 <code v-pre>flag</code> 举个例子吧，假设已知 <code v-pre>flag</code> 是 <code v-pre>cyberpeace{Welcome_to_new_World!}</code>，来计算他的 <code v-pre>Base64</code> 转码之后的值</p>
</blockquote>
<ul>
<li>源字符串：<code v-pre>cyberpeace{Welcome_to_new_World!}</code></li>
<li>ASCII 码：<code v-pre>99 121 98 101 114 112 101 97 99 101 123 87 101 108 99 111 109 101 95 116 111 95 110 101 119 95 87 111 114 108 100 33 125</code>	(空格仅仅是为了看起来方便)</li>
<li>二进制码：<font color=blue>01100011 01111001 01100010</font> 01100101 01110010 01110000 01100101 01100001 01100011 01100101 01111011 01010111 01100101 01101100 01100011 01101111 01101101 01100101 01011111 01110100 01101111 01011111 01101110 01100101 01110111 01011111 01010111 01101111 01110010 01101100 01100100 00100001 01111101	( 每个字节 8 个 bit 位)</li>
<li>Base64：00<font color=blue>011000</font> 00<font color=blue>110111</font> 00<font color=blue>100101 </font>00<font color=blue>100010</font> 00011001 00010111 00001001 00110000 00011001 00010110 00000101 00100011 00011001 00010111 00101101 00010111 00011001 00010110 00110001 00100011 00011011 00110110 00110101 00100101 00010111 00110111 00010001 00101111 00010111 00110110 00111001 00100101 00011101 00110101 00111101 00010111 00011011 00110111 00001001 00101100 00011001 00000010 00000101 00111101	( 每 3 * 8 个 bit， 拆分成 4 * 6 个bit，高位补 2 个 0 凑够 8 bit)</li>
<li>转 10 进制：<code v-pre>24 55 37 34 25 23 9 48 25 22 5 35 25 23 45 23 25 22 49 35 27 54 53 37 23 55 17 47 23 54 57 37 29 53 61 23 27 55 9 44 25 2 5 61 </code>- 转 <code v-pre>Base64</code>编码：<code v-pre>Y3liZXJwZWFjZXtXZWxjb21lX3RvX25ld19Xb3JsZCF9</code>	(<code v-pre>Base64</code> 编码表中，从 0 ~ 63 依次代表：A~Z, a~z, 0~9, +, /）（因为源字符串 <code v-pre>cyberpeace{Welcome_to_new_World!}</code> 的长度为 <code v-pre>33</code>，恰好是 <code v-pre>3</code> 的倍数，被 <code v-pre>Base64</code> 组合成了 33 / 3 * 4 = 44 个字符，所以末尾也不需要 <code v-pre>=</code> 补位）</li>
</ul>
<h1 id="附上测试时使用的转码代码-为了输出整齐-方便观看-有多个冗余的代码块" tabindex="-1"><a class="header-anchor" href="#附上测试时使用的转码代码-为了输出整齐-方便观看-有多个冗余的代码块" aria-hidden="true">#</a> 附上测试时使用的转码代码（为了输出整齐，方便观看，有多个冗余的代码块）</h1>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>
<span class="token keyword">class</span> <span class="token class-name">Solution</span> <span class="token punctuation">{</span>

    <span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token keyword">void</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token class-name">String</span><span class="token punctuation">[</span><span class="token punctuation">]</span> args<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token class-name">String</span> input <span class="token operator">=</span> <span class="token string">"cyberpeace{Welcome_to_new_World!}"</span><span class="token punctuation">;</span>
        <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span>input<span class="token punctuation">.</span><span class="token function">length</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">// String input = "Y3liZXJwZWFjZXtXZWxjb21lX3RvX25ld19Xb3JsZCF9";   // Base64</span>
        <span class="token keyword">char</span><span class="token punctuation">[</span><span class="token punctuation">]</span> chars <span class="token operator">=</span> input<span class="token punctuation">.</span><span class="token function">toCharArray</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token class-name">StringBuilder</span> builder <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">StringBuilder</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">char</span> aChar <span class="token operator">:</span> chars<span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">int</span> n <span class="token operator">=</span> aChar<span class="token punctuation">;</span>
            <span class="token class-name">String</span> binaryString <span class="token operator">=</span> <span class="token class-name">Integer</span><span class="token punctuation">.</span><span class="token function">toBinaryString</span><span class="token punctuation">(</span>n<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token class-name">String</span> str <span class="token operator">=</span> <span class="token class-name">String</span><span class="token punctuation">.</span><span class="token function">format</span><span class="token punctuation">(</span><span class="token string">"%8s"</span><span class="token punctuation">,</span> binaryString<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">replace</span><span class="token punctuation">(</span><span class="token string">" "</span><span class="token punctuation">,</span> <span class="token string">"0"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            builder<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">print</span><span class="token punctuation">(</span>str <span class="token operator">+</span> <span class="token string">" "</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>

        <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>


        <span class="token keyword">int</span> startIndex <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
        <span class="token comment">/* 以下 三个 while 循环代码是几乎完全一样的，只是输出的内容不一样，目的是为了对比看起来方便 */</span>
        <span class="token keyword">while</span> <span class="token punctuation">(</span>builder<span class="token punctuation">.</span><span class="token function">length</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">-</span> startIndex <span class="token operator">>=</span> <span class="token number">6</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
            <span class="token class-name">String</span> substring <span class="token operator">=</span> builder<span class="token punctuation">.</span><span class="token function">substring</span><span class="token punctuation">(</span>startIndex<span class="token punctuation">,</span> <span class="token class-name">Math</span><span class="token punctuation">.</span><span class="token function">min</span><span class="token punctuation">(</span>startIndex <span class="token operator">+</span> <span class="token number">6</span><span class="token punctuation">,</span> builder<span class="token punctuation">.</span><span class="token function">length</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token class-name">String</span> replace <span class="token operator">=</span> <span class="token class-name">String</span><span class="token punctuation">.</span><span class="token function">format</span><span class="token punctuation">(</span><span class="token string">"%8s"</span><span class="token punctuation">,</span> substring<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">replace</span><span class="token punctuation">(</span><span class="token string">" "</span><span class="token punctuation">,</span> <span class="token string">"0"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            startIndex <span class="token operator">=</span> startIndex <span class="token operator">+</span> <span class="token number">6</span><span class="token punctuation">;</span>
            <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">print</span><span class="token punctuation">(</span>replace <span class="token operator">+</span> <span class="token string">" "</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token keyword">int</span> num <span class="token operator">=</span> <span class="token class-name">Integer</span><span class="token punctuation">.</span><span class="token function">parseUnsignedInt</span><span class="token punctuation">(</span>replace<span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token keyword">char</span> c <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">char</span><span class="token punctuation">)</span> num<span class="token punctuation">;</span>
            <span class="token comment">// System.out.print(c);</span>
        <span class="token punctuation">}</span>

        <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

        startIndex <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
        <span class="token keyword">while</span> <span class="token punctuation">(</span>builder<span class="token punctuation">.</span><span class="token function">length</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">-</span> startIndex <span class="token operator">>=</span> <span class="token number">6</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
            <span class="token class-name">String</span> substring <span class="token operator">=</span> builder<span class="token punctuation">.</span><span class="token function">substring</span><span class="token punctuation">(</span>startIndex<span class="token punctuation">,</span> <span class="token class-name">Math</span><span class="token punctuation">.</span><span class="token function">min</span><span class="token punctuation">(</span>startIndex <span class="token operator">+</span> <span class="token number">6</span><span class="token punctuation">,</span> builder<span class="token punctuation">.</span><span class="token function">length</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token class-name">String</span> replace <span class="token operator">=</span> <span class="token class-name">String</span><span class="token punctuation">.</span><span class="token function">format</span><span class="token punctuation">(</span><span class="token string">"%8s"</span><span class="token punctuation">,</span> substring<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">replace</span><span class="token punctuation">(</span><span class="token string">" "</span><span class="token punctuation">,</span> <span class="token string">"0"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            startIndex <span class="token operator">=</span> startIndex <span class="token operator">+</span> <span class="token number">6</span><span class="token punctuation">;</span>
            <span class="token keyword">int</span> num <span class="token operator">=</span> <span class="token class-name">Integer</span><span class="token punctuation">.</span><span class="token function">parseUnsignedInt</span><span class="token punctuation">(</span>replace<span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token keyword">char</span> c <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">char</span><span class="token punctuation">)</span> num<span class="token punctuation">;</span>
            <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">print</span><span class="token punctuation">(</span>num <span class="token operator">+</span> <span class="token string">" "</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>

        <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

        startIndex <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
        <span class="token keyword">while</span> <span class="token punctuation">(</span>builder<span class="token punctuation">.</span><span class="token function">length</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">-</span> startIndex <span class="token operator">>=</span> <span class="token number">6</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
            <span class="token class-name">String</span> substring <span class="token operator">=</span> builder<span class="token punctuation">.</span><span class="token function">substring</span><span class="token punctuation">(</span>startIndex<span class="token punctuation">,</span> <span class="token class-name">Math</span><span class="token punctuation">.</span><span class="token function">min</span><span class="token punctuation">(</span>startIndex <span class="token operator">+</span> <span class="token number">6</span><span class="token punctuation">,</span> builder<span class="token punctuation">.</span><span class="token function">length</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token class-name">String</span> replace <span class="token operator">=</span> <span class="token class-name">String</span><span class="token punctuation">.</span><span class="token function">format</span><span class="token punctuation">(</span><span class="token string">"%8s"</span><span class="token punctuation">,</span> substring<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">replace</span><span class="token punctuation">(</span><span class="token string">" "</span><span class="token punctuation">,</span> <span class="token string">"0"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            startIndex <span class="token operator">=</span> startIndex <span class="token operator">+</span> <span class="token number">6</span><span class="token punctuation">;</span>
            <span class="token keyword">int</span> num <span class="token operator">=</span> <span class="token class-name">Integer</span><span class="token punctuation">.</span><span class="token function">parseUnsignedInt</span><span class="token punctuation">(</span>replace<span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token comment">// base64  0 ~ 25: A ~ Z   26 ~ 51: a ~ z  52 ~ 61: 0 ~ 9   62: +   63: /       填充： =</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>num <span class="token operator">&lt;=</span> <span class="token number">25</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
                <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">print</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token keyword">char</span><span class="token punctuation">)</span><span class="token punctuation">(</span><span class="token char">'A'</span> <span class="token operator">+</span> num<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>num <span class="token operator">></span> <span class="token number">25</span> <span class="token operator">&amp;&amp;</span> num <span class="token operator">&lt;=</span> <span class="token number">51</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
                <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">print</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token keyword">char</span><span class="token punctuation">)</span><span class="token punctuation">(</span><span class="token char">'a'</span> <span class="token operator">+</span> num <span class="token operator">-</span> <span class="token number">26</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>num <span class="token operator">></span> <span class="token number">51</span> <span class="token operator">&amp;&amp;</span> num <span class="token operator">&lt;=</span> <span class="token number">61</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
                <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">print</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token keyword">char</span><span class="token punctuation">)</span><span class="token punctuation">(</span><span class="token char">'0'</span> <span class="token operator">+</span> num <span class="token operator">-</span> <span class="token number">52</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>num <span class="token operator">==</span> <span class="token number">62</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
                <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">print</span><span class="token punctuation">(</span><span class="token string">"+"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>num <span class="token operator">==</span> <span class="token number">63</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
                <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">print</span><span class="token punctuation">(</span><span class="token string">"/"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>builder<span class="token punctuation">.</span><span class="token function">length</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">-</span> startIndex <span class="token operator">&lt;</span> <span class="token number">6</span> <span class="token punctuation">)</span><span class="token punctuation">{</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>builder<span class="token punctuation">.</span><span class="token function">length</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">-</span> startIndex <span class="token operator">==</span> <span class="token number">4</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">print</span><span class="token punctuation">(</span><span class="token string">"="</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>builder<span class="token punctuation">.</span><span class="token function">length</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">-</span> startIndex <span class="token operator">==</span> <span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
                <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">print</span><span class="token punctuation">(</span><span class="token string">"=="</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


